<?php

/**
 * Implements hook_uninstall().
 */
function commerce_Certissim_uninstall() {
    db_drop_field('commerce_order', 'order_status_certissim');
}
  
/**
* Implementation of hook_install().
*/
function commerce_Certissim_install() {
        
$spec = array(
    'type' => 'text',
    'description' => "New order_status_certissim",
    'not null' => FALSE,
  );
  db_add_field('commerce_order', 'order_status_certissim', $spec);
  
 
}